HalProfile/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
	url(r'^$', index, name='index'),
]

add_friend/urls.py
from django.conf.urls import url
from .views import index, add_friend

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_friend', add_friend, name='add_friend')
]

ourApp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView
import add_friend.urls as add_friend
import HalProfile.urls as HalProfile
import update_status2.urls as update_status2
import statistic.urls as statistic
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^friend/', include(add_friend, namespace='friend')),
    url(r'^HalProfile/', include(HalProfile, namespace='HalProfile')),
	url(r'^update/', include(update_status2, namespace='update')),
    url(r'^statistic/', include(statistic, namespace='statistic')),
	url(r'^$',RedirectView.as_view(url='/update/', permanent='true'),name='index'),
]

statistic/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
]

update_status2/urls.py
from django.conf.urls import url
from .views import index, update_status, remove_status


urlpatterns = [
    url(r'^$', index, name='index'),
	url(r'^update_status', update_status, name='update_status'),	
	url(r'^remove_status', remove_status, name='remove_status'),
]

HalProfile/models.py
from django.db import models


# Create your models here.
class DataProfile (models.Model):
	nama =  models.CharField(max_length=250)
	birthday = models.CharField(max_length=20)
	gender = models.CharField(max_length=200)
	expertise = models.TextField( max_length=200)
	description = models.CharField(max_length=200)
	email = models.CharField(max_length=200)

add_friend/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

# Create your models here.
class Friend(models.Model):
    name = models.CharField(max_length=30)
    url = models.URLField()
    

statistic/models.py
from django.db import models

# Create your models here.

update_status2/models.py
from django.db import models

# Create your models here.
class Update(models.Model):
		status = models.TextField()
		created_date = models.DateTimeField(auto_now_add=True)

add_friend/forms.py
from django import forms

class Add_Friend_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
        'invalid': 'tolong isi bentuk url',
    }
    name_attrs = {
        'type': 'text',
        'class': 'form-control ',
        'placeholder':'Masukan name...'
    }
    url_attrs = {
        'type': 'url',
        'class': 'form-control',
        'placeholder':'Masukan url...'
    }
    field = ('nama','url')
    name = forms.CharField(label='Nama', required=True, max_length=30, widget=forms.TextInput(attrs=name_attrs))
    url = forms.URLField(label='Url', required=True, widget=forms.URLInput(attrs=url_attrs))

update_status2/forms.py
from django import forms

class Update_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }
    status_attrs = {
        'type': 'text',
        'cols': 50,
        'rows': 4,
        'class': 'todo-form-textarea',
        'placeholder':'What\'s new?'
    }

    status = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=status_attrs))

HalProfile/views.py
from django.shortcuts import render
from .models import DataProfile

grup_name = "ling-in 12"
birthday = "10 	October 2017" 
gender = 'Female-Male'
expertise = ['Programming', 'Collector','Public Speaking']
description = "ling-in12 yang dimiliki oleh 4 anak manusia, delfa, danin, dennis, hampam"
email = "delfaagustia09@gmail.com"

Profile = DataProfile(nama = grup_name, birthday = birthday, expertise = expertise, description = description, email=email , gender =  gender )
response = {'nama' : Profile.nama, 'birthday' : Profile.birthday, 'expertise' : Profile.expertise, 'description' : Profile.description, 'email':Profile.email , 'gender' :  Profile.gender}

def index(request):
	return render(request, 'HalProfile.html', response)

add_friend/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect

from .forms import Add_Friend_Form
from .models import Friend


# Create your views here.

response = dict()
response['total_friend'] = Friend.objects.count()

def index(request):
    response['content'] = index
    response['author'] = "kelompok 12"
    friend = Friend.objects.all()
    response['friend'] = friend
    response['add_friend_form'] = Add_Friend_Form
    
    html = 'add_friend.html' # html apps lu
    return render(request, html, response)

def add_friend(request):
    form = Add_Friend_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['name'] = request.POST['name']
        response['url'] = request.POST['url']
       
        add = Friend(name=response['name'],url=response['url'])
        add.save()
        return HttpResponseRedirect('/friend/')
    else:
        return HttpResponseRedirect('/friend/')

statistic/views.py
from django.shortcuts import render
from add_friend.views import response
from update_status2.views import response as responseDanin
from HalProfile.views import response as responseDelfa


responseStat = dict()
responseStat.update(response)
responseStat.update(responseDanin)
responseStat.update(responseDelfa)
def index(request):
    return render(request,'statistic.html',responseStat)

update_status2/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Update_Form
from .models import Update
from HalProfile.views import response as responseDelfa

# Create your views here.
response = dict()
response['total_feed'] = Update.objects.count()
response['last_update'] = Update.objects.last()
response.update(responseDelfa)

def index(request):
	update = Update.objects.all().order_by('-created_date')
	
	
	response['update'] = update
	html = 'update_status_new.html'
	response['update_form'] = Update_Form
	
	return render(request, html, response)
	
def update_status(request):
	form = Update_Form(request.POST or None)
	if(request.method == 'POST' and form.is_valid()):
		response['status'] = request.POST['status']
		update = Update(status=response['status'])
		update.save()
		return HttpResponseRedirect('/update/')
	else:
		return HttpResponseRedirect('/update/')
		
def remove_status(request):
    try:
        idStatus = request.POST['flag']
        Update.objects.filter(id=idStatus).delete()
    except ValueError or KeyError:
        pass
    return HttpResponseRedirect('/update/')

HalProfile/templates/HalProfile.html
{% extends "base/base.html" %}}

{% block content %}


<div id="bgDivImage">
  <img src="/static/img/foreHead.jpg" id="bgFrontImage">
  <content class="headFrontImage">
    <div class="container">
      

{% load staticfiles %}
{% load static %}
    <div id = "over" class="text-center">
        <img class="image-fluid"  src = "{% static 'HalProfile/img/pict.jpg' %}" style= "max-width:18%; max-height: 500px;  border-radius: 50%; margin-top: 20px">
        <h2 style="color:white; text-align: center;"><b>{{nama}}</b></h2>
    </div>      
      
    </div>
  </content>
</div>



<div class="container" id="bgContent">
  <content >
  <hr style="border: 1px solid orange" />​

      <h2 style="color:black; text-align: center;"><b>About Us</b></h2>

      <div class="row">
          <table style="width:60%; margin-top: 5px; ;" align= "center";>
          <style>
            table, th, td {
              color: black;
              height: 35px;
              align-content: center;

            }
          </style>
              <tr >
              <th style="width: 30%">Birthday</th>
              <td><b>{{birthday}}</b></td>
              </tr>

              <tr>
              <th >Gender</th>
              <td ><b>{{gender}}</b></td>
              </tr>
              
              <tr>
              <th >Expertise</th>
              <td style = "align = "left">
                <ul>
                {% for ii in expertise %}
                  <li1 style = " padding: 5px; background: orange; color: white; border-radius: 30px; text-align: left; margin-right: 10px">{{ ii }} </li1>
                  {% endfor %}
                </ul>

                </td>
              </tr>

              <tr>
              <th >Description</th>
              <td ><b>{{description}}</b></td>
              </tr>

              <tr>
              <th >Email</th>
              <td ><b>{{email}}</b></td>
              </tr>
          </table>
         
      </div>
       <hr style="border: 1px solid orange">​
  </div>

  </content>
</div>

{% endblock %}  

add_friend/templates/add_friend.html
{% extends "base/base.html" %}}

{% block content %}
<div id="bgDivImage">
	<img src="/static/img/foreHead.jpg" id="bgFrontImage">
	<content class="headFrontImage">
		<div class="container">
			
			<!--
			
			HTML KALIAN YG BAGIAN BACKGROUND GAMBAR MASUKIN DISINI
			
			PERHATIAN, JANGAN bikin class="container" dalam "container" lagi
			
			
			
			
			-->
			<div class="content-center">
	
				<h3>Add Friend</h3>
				
				<form id="formt" method="POST" action="{% url 'friend:add_friend' %}">
					<div class="custom-flex">
						{% csrf_token %}
						{{ add_friend_form.non_field_errors}}
						
						  {% for hidden_field in add_friend_form.hidden_fields %}
							{{ hidden_field.errors }}
							{{ hidden_field }}
						  {% endfor %}
						  
						{% for field in add_friend_form.visible_fields %}
						
							<div class="form-group">
								{{ field.label_tag}}
								{{ field.errors }}
								{{ field }}
								{{ field.help_text }}
							</div>
							{% endfor %}
			
						
						<div class="custom-flex-item" id="button">
							<input id="submit" type="submit" class="btn btn-lg btn-info" value="Submit">
						</div>
						
					</div>
				</form>
				
			</div>
			
		</div>
	</content>
</div>


<div class="container" id="bgContent">
	<content >
	
<div class="headContent">
<section>
	<h3>List Friend</h3>

	<table class="table table-hover">
		<thead>
		  <tr>
			<th>Name</th>
			<th>HerokuApp</th>
		  </tr>
		</thead>
		{% if friend %}
			{% for data in friend %}
			<tbody>
			  <tr>
				<td>{{data.name}}</td>
				<td><a href="{{data.url}}">{{data.url}}</a></td>
			  </tr>
			</tbody>
			{% endfor %}
		{% else %}
			<div class="alert alert-danger text-center">
				<strong>Oops!</strong> kamu tidak memiliki teman.
			</div>
		{% endif %}
	</table>
</section>

</div>
	
	</content>
</div>

{% endblock %}  

add_friend/templates/base/based.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="description" content="Ling-in">
    <meta name="author" content="{{author}}">
	<meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">    
	<link rel="stylesheet" type="text/css" href="{% static 'css/stylesheet.css' %}" />
    <title> 
        {% block title %} Ling-in add friend{% endblock %}
    </title>
</head>

<body>
	<header>
				{% include "extension/header.html" %}
	</header>
	<div class="base" >
		
		<div id="bgDivImage">
			<img src="/static/img/foreHead.jpg" id="bgFrontImage">
			<content class="headFrontImage">
				<div class="container">
					{% include "head.html" %}
				</div>
			</content>
		</div>
		<div class="container" id="bgContent">
			<content >
				
					{% block content %}
					<!-- content goes here -->
					{% endblock %}
				
			</content>
		</div>
		
	</div>
	<footer>
		<!-- TODO Block Footer dan include footer.html -->
		{% block footer %}
		{% include "extension/footer.html" %}
		{% endblock %}
	</footer>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

add_friend/templates/head.html
<div class="content-center">
	
	<h3>Add Friend</h3>
	<form >
		<div class="custom-flex">
			<div class="form-group">
			  <label for="usr">Name:</label>
			  <input type="text" class="form-control" id="usr">
			</div>
			<div class="form-group">
			  <label for="pwd">Password:</label>
			  <input type="password" class="form-control" id="pwd">
			</div>
		</div>
	</form>
	
</div>

statistic/templates/statistic.html
{% extends "base/base.html" %}}
{% load staticfiles %}
{% block content %}
<div id="bgDivImage">
	<img src="/static/img/foreHead.jpg" id="bgFrontImage">
	<content class="headFrontImage">
		<div class="container">
			
			<!--
			HTML KALIAN YG BAGIAN BACKGROUND GAMBAR MASUKIN DISINI
			
			PERHATIAN, JANGAN bikin class="container" dalam "container" lagi
			-->
			
				  
			{% load staticfiles %}
			{% load static %}
				<div id = "over" class="text-center">
					<img class="image-fluid"  src = "{% static 'HalProfile/img/pict.jpg' %}" style= "max-width:20%; max-height: 900px;  border-radius: 50%; margin-top: 20px">
					<h2 style="color:white; text-align: center;"> <b>{{nama}} </b> </h2>
				</div>      
				
			  
			
			
		</div>
	</content>
</div>


<div class="container" id="bgContent">
	<content >
		
		<!--
			
			HTML KALIAN YG BAGIAN BACKGROUND PUTIH
			
			PERHATIAN, JANGAN bikin class="container" dalam "container" lagi
			
			
			
			
			-->
			<div class="row">
				<br></br>
				
				<div class="col-sm-12" >
				  <br></br>
				  <h2>Statistics</h2>
				  <hr/>
				  
				  <div class="row">
					  <div class="col-sm-6" >
						<br></br>
						
						<p><span style="font-weight: bold; margin: 50px 50px 50px 0">Friends</span> {{total_friend}} people</p>
						<h6 style="font-weight: bold; margin: 50PX 50PX 50PX 0">Latest Post 
							<br></br>	
							{% if last_update %}
								
									<div class="flex-item">
										<div class="to-do-list">
											<div class="image-and-username">
												<p>
												<img src="{% static 'HalProfile/img/pict.jpg' %}" width='50px' height='50px' align="middle">
												<b>
												{{author}}
												</b>
												</p>
											</div>
											<div class="to-do-list-description">
												{{last_update.status}}
											</div>
											<div class="to-do-list-date-added">
												<font color='gray'>
												{{last_update.created_date}}
												</font>
											</div>
											<form id="form-{{data.id}}" method="post" action="{% url 'update:remove_status' %}">
												{% csrf_token %}
												<input type="hidden" name="flag" value="{{data.id}}"/>
												
											</form>
										</div>
									</div>
								
							{% else %}
							<div class="alert alert-danger text-center">
								<strong>Oops!</strong> Tidak ada data.
							</div>
							{% endif %}
						</h6>
					  </div>
					  <div class="col-sm-6" >
						  <br></br>
						  
						<p><span style="font-weight: bold; margin: 50PX 50PX 50px 0">Feed</span>{{total_feed}}</p>
					  </div>
				  </div>
	  
				</hr>
				</div>
			  </div>
	</content>
</div>

{% endblock %}  

templates/base/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="description" content="Ling-in">
    <meta name="author" content="{{author}}">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script> <!-- bootstrap csss -->
	<link rel="stylesheet" href="{% static 'home/css/bootstrap.min.css' %}" type = "text/css"/>
	<link rel="stylesheet" type="text/css" href="{% static 'css/stylesheet.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'headerfooter.css' %}" />
    <title> 
        {% block title %}{% endblock %}
    </title>
</head>

<body>
	<header>
		{% include "partials/header.html" %}
	</header>
	<div class="base" >
		{% block content %}
					<!-- content goes here -->
		{% endblock %}

	</div>
	<footer >
		<!-- TODO Block Footer dan include footer.html -->
		{% block footer %}
		{% include "partials/footer.html" %}
		{% endblock %}
	</footer>

    <!-- Jquery n Bootstrap Script -->
    
</body>
</html>

templates/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="description" content="Ling-in">
    <meta name="author" content="{{author}}">
	<meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">    
	<link rel="stylesheet" type="text/css" href="{% static 'css/stylesheet.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
    <title> 
        {% block title %} Ling-in add friend{% endblock %}
    </title>
</head>

<body>
	<header>
				{% include "partials/header.html" %}
	</header>
	<div class="base" >
		
		<div id="bgDivImage">
			<img src="/static/img/foreHead.jpg" id="bgFrontImage">
			<content class="headFrontImage">
				<div class="container">
					{% include "head.html" %}
				</div>
			</content>
		</div>
		<div class="container" id="bgContent">
			<content >
				
					{% block content %}
					<!-- content goes here -->
					{% endblock %}
				
			</content>
		</div>
		
	</div>
	<footer>
		<!-- TODO Block Footer dan include footer.html -->
		{% block footer %}
		{% include "partials/footer.html" %}
		{% endblock %}
	</footer>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

templates/partials/footer.html
<p>Posted by: Kami cinta PPW team 12</p>
<p>Contact information: <a href="mailto:someone@example.com">
ilham.pamungkas@ui.ac.id</a>.</p>

templates/partials/header.html
{% load staticfiles %}

<nav class="navbar navbar-default navbar-expand-lg navbar-dark fixed-top ">
        <img class="navbar-brand" src="{% static 'home/logoInvert.png' %}" href="#">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="/update/">Status</a>
            </li>
            <li class="nav-item" >
              <a class="nav-link" href="/HalProfile/">Profile</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/friend/">Friends</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/statistic/">Stats</a>
            </li>
          </ul>
        </div>
      </nav>

templates/template.html
{% extends "base/base.html" %}}

{% block content %}
<div id="bgDivImage">
	<img src="/static/img/foreHead.jpg" id="bgFrontImage">
	<content class="headFrontImage">
		<div class="container">
			
			<!--
			
			HTML KALIAN YG BAGIAN BACKGROUND GAMBAR MASUKIN DISINI
			
			PERHATIAN, JANGAN bikin class="container" dalam "container" lagi
			
			-->
			
			
		</div>
	</content>
</div>


<div class="container" id="bgContent">
	<content >
	
		<!--
			
			HTML KALIAN YG BAGIAN BACKGROUND PUTIH
			
			PERHATIAN, JANGAN bikin class="container" dalam "container" lagi
		
		 	
			-->
	
	</content>
</div>

{% endblock %}  

update_status2/templates/update_status.html
{% extends "layout/base2.html" %}

{% block content %}
<section name="input-list" id="input-list">
			<div class="container">
				<form id="form" method="POST" action="{% url 'update:update_status' %}">
					{% csrf_token %}
					{{ update_form }}
					<input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Submit">
					<br>
				</form>
			</div>
</section>
<section name="my-list" id="my-list">
    <div class="container">
        <div class="flex">
            {% if update %}
                {% for data in update %}
                    <div class="flex-item">
                        <div class="to-do-list">
							<div class="image-and-username">
								<p>
								<img src="https://pbs.twimg.com/media/CdWxbnvW8AAAvmi.jpg" width='50px' height='50px' align="middle">
								<b>
								{{author}}
								</b>
								</p>
							</div>
							<div class="to-do-list-description">
                                {{data.status}}
                            </div>
                            <div class="to-do-list-date-added">
								<font color='gray'>
                                {{data.created_date}}
								</font>
                            </div>
							<form id="form-{{data.id}}" method="post" action="{% url 'update:remove_status' %}">
								{% csrf_token %}
								<input type="hidden" name="flag" value="{{data.id}}"/>
								<input id = "submit{{data.id}}" id="delete-{{data.id}}" type="submit" data-id="{{data.id}}" value="Delete" class="to-do-list-delete">
							</form>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
            <div class="alert alert-danger text-center">
                <strong>Oops!</strong> Tidak ada data.
            </div>
            {% endif %}
        </div>
    </div>
</section>
{% endblock %}

update_status2/templates/update_status_new.html
{% extends "base/base.html" %}}
{% load staticfiles %}
{% block content %}
<div id="bgDivImage">
	<img src="/static/img/foreHead.jpg" id="bgFrontImage">
	<content class="headFrontImage">
		<div class="container">
			

			


			<form id="form" method="POST" action="{% url 'update:update_status' %}">
					{% csrf_token %}
					{{ update_form }}
					<div class="pull-right">
						
					   
					<input id="submit" type="submit" class="btn btn-lg input-lg btn-info" value="Submit">
					</div>
					<br>
				</form>
			
			
		</div>
	</content>
</div>


<div class="container" id="bgContent">
	<content >
	
		<div class="flex">
            {% if update %}
                {% for data in update %}
                    <div class="flex-item">
                        <div class="to-do-list">
							<div class="image-and-username">
								<p>
								<img class="image-fluid"  src = "{% static 'HalProfile/img/pict.jpg' %}" style= "max-width:70px; max-height: 70px;  border-radius: 50%">
								<b>
								{{nama}}
								</b>
								</p>
							</div>
							<div class="to-do-list-description">
                                {{data.status}}
                            </div>
                            <div class="to-do-list-date-added">
								<font color='gray'>
                                {{data.created_date}}
								</font>
                            </div>
							<form id="form-{{data.id}}" method="post" action="{% url 'update:remove_status' %}">
								{% csrf_token %}
								<input type="hidden" name="flag" value="{{data.id}}"/>
								<input id = "submit{{data.id}}" id="delete-{{data.id}}" type="submit" data-id="{{data.id}}" value="Delete" class="to-do-list-delete">
							</form>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
            <div class="alert alert-danger text-center">
                <strong>Oops!</strong> Tidak ada data.
            </div>
            {% endif %}
        </div>
	
	</content>
</div>

{% endblock %}  

update_status2/templates/updater.html
<div class="content-center">
	
	<h3>Test</h3>
	<font color="black">
		<div class="custom-flex">
			<!--{% csrf_token %}
                {{ add_friend_form }}
			<div class="custom-flex-item" id="button">
				<button type="submit" class="btn btn-default">Submit</button>
			</div>
			-->
			<section name="input-list" id="input-list">
			<div class="container">
				<form id="form" method="POST" action="{% url 'update:update_status' %}">
					{% csrf_token %}
					{{ update_form }}
					<input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Submit">
					<br>
				</form>
			</div>
			</section>
		</div>
	</font>
	
</div>